steps:

  # Build app

  # Deploy

  # Canary 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'update-traffic', 'hello',
          '--region', 'us-central1',
          '--to-revisions=LATEST=0']
    id: CANARY
